# Generated by Django 4.2 on 2023-04-06 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_data_team_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data'},
        ),
    ]
